FROM node:16

# Create app directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# DEBUG: incluso nel container, i pacchetti sono già presenti
# COPY package*.json ./

# RUN npm install

# Bundle app source
COPY . .

EXPOSE 5000

ENV IP 0.0.0.0
ENV PORT 5000
# TPER news server has bad TSL signature, unfortunately this is necessary
# RUN sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/g' openssl.cnf

CMD [ "npm", "run", "dev" ]